server:
  port: 7010
spring:
  application:
    name: pay-system-member-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#eureka:
#  client:
#    service-url:
#      defaultZone: http://payhost:8761/eureka/
