server:
  port: 8100
spring:
  application:
    name: pay-system-gateway
#  cloud:
#    gateway:
#      routes:
#      - id: jd_route
#        uri: http://www.jd.com
#        predicates:
#          - Path=/jingdong
#      - id: pay-system-member-service-router
#        uri: lb://pay-system-member-consumer
#        predicates:
#          - Path=/member
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
